export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const ANNOUNCEMENT_LOADING = 'ANNOUNCEMENT_LOADING';
export const ANNOUNCEMENT_FAILED = 'ANNOUNCEMENT_FAILED';
export const ADD_ANNOUNCEMENTS = 'ADD_ANNOUNCEMENTS'

export const ADD_POSTS = 'ADD_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const ADD_POST = 'ADD_POST'

export const ADD_TOPPERS = 'ADD_TOPPERS';
export const TOPPERS_LOADING = 'TOPPERS_LOADING';
export const TOPPERS_FAILED = 'TOPPERS_FAILED';

export const ADD_PLACEMENTS = 'ADD_PLACEMENTS';
export const PLACEMENTS_LOADING = 'PLACEMENTS_LOADING';
export const PLACEMENTS_FAILED = 'PLACEMENTS_FAILED';

export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
export const FEEDBACK_FAILED = 'FEEDBACK_FAILED';
export const ADD_FEEDBACKS = 'ADD_FEEDBACKS';

export const ADD_PRAYAANAS = 'ADD_PRAYAANAS';
export const PRAYAANA_LOADING = 'PRAYAANA_LOADING';
export const PRAYAANA_FAILED = 'PRAYAANA_FAILED';

export const ADD_PIZADA = 'ADD_PIZADA';
export const ADD_PIZADAS = 'ADD_PIZADAS';
export const PIZADA_LOADING = 'PIZADA_LOADING';
export const PIZADA_FAILED = 'PIZADA_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';





